language: go
go:
  - 1.12
env:
  - GO111MODULE=on
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.15.0
script:
  - golangci-lint run ./...
